"""Offline TEMPEST-LoRa laboratory transfer protocol, profile, and renderer contracts."""

from .input_policy import DEFAULT_INPUT_ROOT, SyntheticFixture, read_synthetic_fixture
from .oracle_adapter import PinnedOracleRuntime, execute_pinned_oracle
from .oracle_boundary import (
    OracleRequest,
    load_and_validate_request,
    load_and_validate_result,
    write_request,
    write_result,
)
from .pixel_renderer import (
    CaptureReplayArtifact,
    DynamicRenderedPixelArtifact,
    render_dynamic_envelope,
    replay_capture_fixture,
)
from .profiles import (
    CAPTURE_GOLDEN_CANONICAL_PGM_SHA256,
    CAPTURE_GOLDEN_DECODED_RAW_SHA256,
    CAPTURE_GOLDEN_IMAGE_FIXTURE_SHA256,
    CAPTURE_GOLDEN_SYMBOL_FIXTURE_SHA256,
    CAPTURE_GOLDEN_SYMBOLS_SHA256_UINT16BE,
    CAPTURE_GOLDEN_SYMBOLS_ZERO_BASED,
    PINNED_ORACLE_COMMIT,
    PINNED_ORACLE_TREE,
    CaptureReplayRendererProfile,
    DynamicPhyParameters,
    DynamicPixelRendererProfile,
    SymbolEnvelope,
    capture_profile_descriptor,
    dynamic_profile_descriptor,
    normalize_capture_symbols,
    normalize_dynamic_symbols,
)
from .protocol import (
    HEADER_BYTES,
    MAX_FIXTURE_BYTES,
    MAX_FRAGMENT_COUNT,
    MAX_FRAGMENT_PAYLOAD_BYTES,
    MAX_LORA_PAYLOAD_BYTES,
    FrameType,
    ProfileId,
    ProtocolError,
    build_transfer_frames,
    parse_frame,
    reassemble_transfer,
)

__all__ = [
    "CAPTURE_GOLDEN_CANONICAL_PGM_SHA256",
    "CAPTURE_GOLDEN_DECODED_RAW_SHA256",
    "CAPTURE_GOLDEN_IMAGE_FIXTURE_SHA256",
    "CAPTURE_GOLDEN_SYMBOL_FIXTURE_SHA256",
    "CAPTURE_GOLDEN_SYMBOLS_SHA256_UINT16BE",
    "CAPTURE_GOLDEN_SYMBOLS_ZERO_BASED",
    "CaptureReplayArtifact",
    "CaptureReplayRendererProfile",
    "DEFAULT_INPUT_ROOT",
    "DynamicPhyParameters",
    "DynamicPixelRendererProfile",
    "DynamicRenderedPixelArtifact",
    "FrameType",
    "HEADER_BYTES",
    "MAX_FIXTURE_BYTES",
    "MAX_FRAGMENT_COUNT",
    "MAX_FRAGMENT_PAYLOAD_BYTES",
    "MAX_LORA_PAYLOAD_BYTES",
    "OracleRequest",
    "PINNED_ORACLE_COMMIT",
    "PINNED_ORACLE_TREE",
    "PinnedOracleRuntime",
    "ProfileId",
    "ProtocolError",
    "SymbolEnvelope",
    "SyntheticFixture",
    "build_transfer_frames",
    "capture_profile_descriptor",
    "dynamic_profile_descriptor",
    "execute_pinned_oracle",
    "load_and_validate_request",
    "load_and_validate_result",
    "normalize_capture_symbols",
    "normalize_dynamic_symbols",
    "parse_frame",
    "read_synthetic_fixture",
    "reassemble_transfer",
    "render_dynamic_envelope",
    "replay_capture_fixture",
    "write_request",
    "write_result",
]
